name: CI
on:
  workflow_dispatch:
    inputs:
      dispatchDeploy:
        description: Deploy if there are changes? ('true')
        required: true
        default: 'true'
  push:
  schedule:
    - cron: '23 1 * * *'

jobs:
  build:
    name: CI
    strategy:
      matrix:
        ref: '${{ fromJson((''workflow_dispatch'' == github.event_name) && ''[ "refs/heads/release/2.x.x", "refs/heads/release/3.x.x" ]'' || format(''[ {0} ]'', toJson(github.ref))) }}'
    runs-on: windows-2019
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Log debug
        env:
          REFXYZ: ${{ matrix.ref }}
          ACTION_DISPATCH_DEPLOY: ${{ github.event.inputs.dispatchDeploy }}
        shell: pwsh
        run: |
          Write-Host $env:REFXYZ
          Write-Host $env:ACTION_DISPATCH_DEPLOY
          Write-Error 'HELLO WORLD'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ matrix.ref }}
