name: CI
on:
  workflow_dispatch:
  push:
    tags:
    - 'v/*'
    branches:
    - release/3.x.x
    - release/2.x.x
  schedule:
    - cron: '23 1 * * *'

jobs:
  build:
    name: CI
    runs-on: windows-2019
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Test
        shell: pwsh
        env:
          ACTIONS_REFS_TEST: |
            ${{ toJson(fromJson(
              ('schedule' == github.event_name)
              && '[ "refs/heads/release/2.x.x", "refs/heads/release/3.x.x" ]'
              || format('[ {0} ]', toJson(github.ref))
            )) }}
        run: Write-Host $env:ACTIONS_REFS_TEST
