name: CI
on:
  workflow_dispatch:
  push:
    tags:
    - 'v/*'
    branches:
    - release/3.x.x
    - release/2.x.x
  schedule:
    - cron: '23 1 * * *'

jobs:
  build:
    name: CI
    strategy:
      matrix: |
        ${{ fromJson(
          ('schedule' == github.event_name)
          && '{ "ref": [ "refs/heads/release/2.x.x", "refs/heads/release/3.x.x" ] }'
          || format('{{ "ref": [ {0} ] }}', toJson(github.ref))
        ) }}
    runs-on: windows-2019
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.ref }}
